{{- if .Values.controller.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: controller
    {{- include "mosfs-csi.labels" . | nindent 4 }}
  name: mosfs-csi-controller
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: mosfs-csi-controller
      {{- include "mosfs-csi.selectorLabels" . | nindent 6 }}
  serviceName: mosfs-csi-controller
  template:
    metadata:
      labels:
        app: mosfs-csi-controller
        {{- include "mosfs-csi.selectorLabels" . | nindent 8 }}
    spec:
    {{- if .Values.hostAliases }}
      hostAliases:
      {{- toYaml .Values.hostAliases | nindent 6 }}
    {{- end }}
      containers:
      - name: mosfs-plugin
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        {{- if .Values.image.pullPolicy }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- end }}
        args:
        - --endpoint=$(CSI_ENDPOINT)
        - --logtostderr
        - --nodeid=$(NODE_ID)
        - --v=5
        env:
        - name: CSI_ENDPOINT
          value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MOSFS_MOUNT_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MOSFS_MOUNT_PATH
          value: {{ .Values.mosfsMountDir }}
        - name: MOSFS_CONFIG_PATH
          value: {{ .Values.mosfsConfigDir }}
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
        resources:
          {{- toYaml .Values.controller.resources | nindent 10 }}
        ports:
        - containerPort: 9909
          name: healthz
          protocol: TCP
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/csi/sockets/pluginproxy/
          name: socket-dir
        - mountPath: /etc/ceph
          name: ceph-conf
        - mountPath: /mosfs
          mountPropagation: Bidirectional
          name: mosfs-dir
        - mountPath: /root/.juicefs
          mountPropagation: Bidirectional
          name: mosfs-root-dir
      - name: csi-snapshotter
        image: {{ printf "%s:%s" .Values.sidecars.csiSnapshotterImage.repository .Values.sidecars.csiSnapshotterImage.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "--csi-address=$(ADDRESS)"
          - "--timeout=60s"
          - "--v=5"
        env:
          - name: ADDRESS
            value: /var/lib/csi/sockets/pluginproxy/csi.sock
          - name: TZ
            value: "Asia/Shanghai"
        volumeMounts:
          - name: socket-dir
            mountPath: /var/lib/csi/sockets/pluginproxy/
      - name: csi-resizer
        image: {{ printf "%s:%s" .Values.sidecars.csiResizerImage.repository .Values.sidecars.csiResizerImage.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - "--csi-address=$(ADDRESS)"
          - "--v=5"
          - "--timeout=60s"
        env:
          - name: ADDRESS
            value: /var/lib/csi/sockets/pluginproxy/csi.sock
        volumeMounts:
          - name: socket-dir
            mountPath: /var/lib/csi/sockets/pluginproxy/
      - name: csi-provisioner
        image: {{ printf "%s:%s" .Values.sidecars.csiProvisionerImage.repository .Values.sidecars.csiProvisionerImage.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --csi-address=$(ADDRESS)
        - --timeout=60s
        - --v=5
        env:
        - name: ADDRESS
          value: /var/lib/csi/sockets/pluginproxy/csi.sock
        volumeMounts:
        - mountPath: /var/lib/csi/sockets/pluginproxy/
          name: socket-dir
      - name: liveness-probe
        image: {{ printf "%s:%s" .Values.sidecars.livenessProbeImage.repository .Values.sidecars.livenessProbeImage.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --csi-address=$(ADDRESS)
        - --health-port=$(HEALTH_PORT)
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        - name: HEALTH_PORT
          value: "9909"
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      priorityClassName: system-cluster-critical
      serviceAccount: {{ include "mosfs-csi.controller.serviceAccountName" . }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - emptyDir: {}
        name: socket-dir
      - hostPath:
          path: {{ .Values.mosfsMountDir }}
          type: DirectoryOrCreate
        name: mosfs-dir
      - hostPath:
          path: {{ .Values.mosfsConfigDir }}
          type: DirectoryOrCreate
        name: mosfs-root-dir
      - secret:
          secretName: ceph-conf
        name: ceph-conf
{{- end }}
