{{- if .Values.serviceAccount.controller.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mosfs-csi.controller.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mosfs-csi.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.controller.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mosfs-csi-external-provisioner-role
  labels:
    {{- include "mosfs-csi.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
    - persistentvolumes
  verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
- apiGroups:
    - ""
  resources:
    - persistentvolumeclaims
  verbs:
    - get
    - list
    - watch
    - update
- apiGroups: [""]
  resources: ["persistentvolumeclaims/status"]
  verbs: ["update", "patch"]
- apiGroups:
    - storage.k8s.io
  resources:
    - storageclasses
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
- apiGroups:
    - storage.k8s.io
  resources:
    - csinodes
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - nodes
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
    - list
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshotclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshotcontents"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshotcontents/status"]
  verbs: ["update"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshots"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "mosfs-csi.labels" . | nindent 4 }}
  name: mosfs-csi-provisioner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mosfs-csi-external-provisioner-role
subjects:
- kind: ServiceAccount
  name: {{ include "mosfs-csi.controller.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
{{- end }}
---
{{- if .Values.serviceAccount.node.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mosfs-csi.node.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mosfs-csi.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mosfs-csi-external-node-service-role
  labels:
    {{- include "mosfs-csi.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - nodes/proxy
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "mosfs-csi.labels" . | nindent 4 }}
  name: mosfs-csi-node-service-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mosfs-csi-external-node-service-role
subjects:
  - kind: ServiceAccount
    name: {{ include "mosfs-csi.node.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
{{- end }}
---
{{- if .Values.serviceAccount.snapshotController.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mosfs-csi.snapshotController.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mosfs-csi.labels" . | nindent 4 }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: snapshot-controller-role
  labels:
    {{- include "mosfs-csi.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots/status"]
    verbs: ["update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: snapshot-controller-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "mosfs-csi.snapshotController.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: snapshot-controller-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
---
{{- if .Values.warmup.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cache-controller
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: warmup-role
  labels:
    {{- include "mosfs-csi.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - cache.sandstone.com
    resources:
      - caches
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cache.sandstone.com
    resources:
      - caches/finalizers
    verbs:
      - update
  - apiGroups:
      - cache.sandstone.com
    resources:
      - caches/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/attach
      - pods/exec
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs: ["get", "watch", "list", "delete", "update", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: warmup-rolebinding
  labels:
    {{- include "mosfs-csi.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: warmup-role
subjects:
  - kind: ServiceAccount
    name: cache-controller
    namespace: {{ .Values.namespace }}
{{- end }}