---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: csi-mosfsplugin-snapshotclass
driver: csi-sandstone-mosfsplugin
deletionPolicy: Delete
parameters:
    csi.storage.k8s.io/snapshotter-secret-name: mosfs-secret
    csi.storage.k8s.io/snapshotter-secret-namespace: default


