---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: csi-mosfs-pvc-snapshot
spec:
  volumeSnapshotClassName: csi-mosfsplugin-snapshotclass
  source:
    persistentVolumeClaimName: mosfs-pvc


