apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mosfs-sc
provisioner: csi-sandstone-mosfsplugin
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/provisioner-secret-name: mosfs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/node-publish-secret-name: mosfs-secret
  csi.storage.k8s.io/node-publish-secret-namespace: default
  csi.storage.k8s.io/controller-expand-secret-name: mosfs-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: default