---
apiVersion: v1
kind: Pod
metadata:
  name: mosfs-demo-pod-rados
spec:
  containers:
    - name: busybox
      image: busybox:1.34.0
      command: ["/bin/sh"]
      args: ["-c", "sleep infinity"]
      volumeMounts:
        - name: mypvc
          mountPath: /mnt
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: mosfs-pvc-rados
        readOnly: false

