apiVersion: v1
metadata:
  name: mosfs-secret-rados
  namespace: default
kind: Secret
type: Opaque
stringData:
  name: csitest-rados
  token: a639584b325ef422688215009253a68f5dc48178
  consoleToken: 6b175b78b974e4121bb4dbf9e7ae3568ab2ce901
  storage: ceph
  accesskey: ceph
  secretkey: client.admin
  configs: '{"ceph-conf": "/etc/ceph"}'
  envs: '{"BASE_URL": "http://20.20.51.211:20101/static","CFG_URL": "http://20.20.51.211:20101/volume/%s/mount"}'
