---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosfs-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: mosfs-sc
