---
apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: csi-mosfs-pvc-snapshot
spec:
  snapshotClassName: csi-mosfsplugin-snapshotclass
  source:
    name: mosfs-pvc
    kind: PersistentVolumeClaim


