apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
  labels:
    fs-name: mosfs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: csi-sandstone-mosfsplugin
    fsType: ext4
    nodePublishSecretRef:
      name: mosfs-sc-bucket-secret
      namespace: sandstone
    volumeHandle: static-pv
    volumeAttributes:
      subPath: your-subDir
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
