---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosfs-pvc-restore
spec:
  storageClassName: mosfs-sc-bucket
  dataSource:
    name: csi-mosfs-pvc-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
